### ISSUE TITLE
Website Heroku Application Error

### ISSUE THREAD

**Issue by GalaxyLittlepaws** [FurryCoders/Furry-Badges#1]
The website linked on the repo here is not working: [furry-badges.herokuapp.com](https://furry-badges.herokuapp.com/).

This is the screen that appears when opening it:
![image](https://github.com/FurryCoders/Furry-Badges/assets/34807062/b53f7bbb-8bb9-4845-adaf-996b13386f26)

I would assume this is due to Heroku revoking all their free hosting options.

**Comment by MatteoCampinoti94** [comment]
My other Heroku apps used up all the "dynos" hours I subscribed for :(

I will move the app to a new platform, Heroku has been quite bad as of late and their pricing is just too high for a simple hobby project.

**Comment by GalaxyLittlepaws** [comment]
Glad to hear you're moving it, I came across this and would love to try it out.

**Comment by MatteoCampinoti94** [comment]
The new site is ready, but my hosting provider has a _very_ strict security policy so shields.io cannot access the endpoint. It should hopefully be working properly in just a few hours once they modify the firewall settings :)

**Comment by MatteoCampinoti94** [comment]
It took longer than k hoped to get an answer, but the site is finally back online at https://furry-badges.codingfoxden.dk :3

Enjoy your ![](https://furry-badges.codingfoxden.dk/badge/svg/user/furry/Badges!/Furry) ^.^
